import json
from pathlib import Path

def record_behavior(run_result: dict) -> dict:
    """
    Parses the standard output from the wrapper to extract the serialized JSON object.
    """
    stdout = run_result["stdout"]
    json_output = None
    
    # Parse the output generated by SafetyNetWrapper
    # We look for the specific marker "###SAFETYNET_RESULT###"
    for line in stdout.splitlines():
        if line.startswith("###SAFETYNET_RESULT###"):
            json_str = line.replace("###SAFETYNET_RESULT###", "")
            try:
                json_output = json.loads(json_str)
            except json.JSONDecodeError:
                print("Error: Failed to parse JSON output from wrapper.")

    snapshot = {
        "exit_code": run_result["exit_code"],
        "captured_return_value": json_output, # We are now capturing the actual object state
        "raw_stdout": stdout,  # Kept for debugging purposes
        "stderr": run_result.get("stderr", "")
    }
    return snapshot

def save_snapshot(project_path: str, snapshot: dict) -> str:
    """
    Persists the captured snapshot to a JSON file.
    """
    out_dir = Path(project_path) / ".safetynet"
    out_dir.mkdir(exist_ok=True)

    out_file = out_dir / "snapshot.json"
    out_file.write_text(json.dumps(snapshot, indent=2), encoding="utf-8")
    return str(out_file)